project:
  type: website

website:
  title: "Informacion Diabetes con QUARTO"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/burrejolag
      - icon: youtube
        href: https://www.youtube.com/watch?v=0SE_XjWJLvA
format:
  html:
    theme: minty
    css: styles.css

editor: visual

